resources:
  repositories:
  - repository: ci
    type: github
    name: arcnmx/ci
    ref: refs/heads/master
    endpoint: github/arcnmx/ci
variables:
  CI_ALLOW_ROOT: true
  CI_CLOSE_STDIN: true
  TERM: linux
jobs:
- job: test
  pool:
    vmImage: $(vmImage)
  strategy:
    matrix:
      linux:
        vmImage: ubuntu-latest
      highsierra:
        vmImage: macos-10.13
      mojave:
        vmImage: macos-10.14
  steps:
  - template: azure/nix/install.yml@ci
    parameters:
      config: azure/ci.nix
      ciVersion: master
  - bash: nix-build -E '(import ./. {}).yosys'
    displayName: nix build yosys
  - bash: nix-build -E '(import ./. {}).nextpnr'
    displayName: nix build nextpnr
  - bash: ./result/bin/nextpnr-ice40 --version
    displayName: version
    continueOnError: true
  - bash: ./result/bin/nextpnr-ice40 --help
    displayName: help
    continueOnError: true
  - bash: ./result/bin/nextpnr-ice40 --gui
    displayName: gui
    timeoutInMinutes: 1
    continueOnError: true
